DROP DATABASE IF EXISTS movie_db;

CREATE DATABASE IF NOT EXISTS movie_db;

USE movie_db;

CREATE TABLE IF NOT EXISTS movies (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  directed_by VARCHAR(100) NOT NULL,
  release_year INT NOT NULL
);

SELECT * FROM movies;