version: '3.5'

services:

  mongo:
    image: mongosh
    container_name: mongodb
    working_dir: /db
    volumes:
      - ./
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senhaultrasecreta
  restart: always
